-- INSERT USERS
INSERT INTO user (username, password, firstname, lastname, email, date_registration, imgurl) VALUES
('admin', '$2a$11$rVf18ZL7N9gxJ56.y8Q8e.1L6lgPSf.QyTR195po0AACzETms2DZW', 'Diksha', 'Bhutekar',
 'admin@ves.com', '2023-02-16', 'https://i.imgur.com/k4k1fOM.png'),
('user', '$2a$11$94oXCXGGei6OmJOXGX4u.eP0bun7PXmwQmfYVJi1BLzyB4JKoPF1.', 'Nikita', 'Patond', 'user@ves.com', '2023-02-16', 'https://i.imgur.com/k4k1fOM.png');
-- INSERT ROLES
INSERT INTO auth_user_group (username, auth_group) VALUES('admin', 'ADMIN');
INSERT INTO auth_user_group (username, auth_group) VALUES('user', 'USER');
-- INSERT TEACHERS
INSERT INTO teacher (firstname, lastname, email, description, details, imgurl) VALUES
('Riya', 'Ganguly', 'riya.g@gmail.com', 'Science Teacher', 'I am a Msc Graduate. I am expert in Science. I have 5 years of experience in teaching field. I have taught and mentored 1000s of students in my career.', 'https://i.imgur.com/swUNc4x.jpg'),
('Parag', 'Kumar', 'parag.k@gmail.com', 'Math Teacher', 'I am a ME Mechanical Engineer. I am expert in Mathematics. I have 6 years of experience in teaching field. I have taught and mentored 2000s of students in my career.', 'https://i.imgur.com/b2kSFna.jpg'),
('Kalpana', 'More', 'kalpana.m@outlook.com', 'Social Science Teacher', 'I am a Msc graduate. I love to teach social science. I have 6 years of experience in teaching field. I have taught and mentored 2000s of students in my career.', 'https://i.imgur.com/l053VCb.jpg'),
('Anand', 'Saha', 'anand.k@yahoo.com', 'English Teacher', 'I have completed MA in English. I am expert in teaching english. I have 4 years of experience in teaching field. I have taught and mentored 1000s of students in my career.', 'https://i.imgur.com/WMypv2A.jpg'),
('Ajay', 'Kumar', 'ajay.k@hotmail.com', 'Sanskrit Teacher','I have completed MA in Sanskrit. I am expert in teaching sanskrit. I have 3 years of experience in teaching field. I have taught and mentored 1000s of students in my career.', 'https://i.imgur.com/Olu2PuN.jpg'),
('Suraj', 'Gaikwad', 'suraj.g@hotmail.com', 'Chemistry Teacher', 'I am M.Tech Chemical Engineer. I am expert in chemistry. I have 7 years of experience in teaching field. I have taught and mentored 4000s of students in my career.', 'https://i.imgur.com/r6yq088.jpg'),
('Diya', 'Talwar', 'diya.t@gmail.com', 'Biology Teacher', 'I am a biology teacher with 10 years of experience in this subject. I have 5 years of experience in teaching field. I have taught and mentored 3000s of students in my career.', 'https://i.imgur.com/WwVezDt.jpg'),
('Alok', 'Sinha', 'alok.s@outlook.com', 'Physics Teacher', 'I am a Electrical Engineer. I have 5 years of experience in teaching field. I love to teach physics. I have taught and mentored 3000s of students in my career.', 'https://i.imgur.com/rtb0xJF.jpg');
-- INSERT COURCES
INSERT INTO course (name, description, teacher_id, details, difficulty, url, imgurl) VALUES
( 'Class - 5th', 'Subjects - Science, Maths, English, Social Science', 1, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Easy', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/R6pDcTz.jpeg'),
( 'Class - 8th', 'Subjects - Science, Maths, English, Sanskrit',4, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Intermediate', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/K7yQTXE.png'),
( 'NEET Batch', 'Subjects - Physics, Chemistry, Biology', 7, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Advance', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/sCyCb07.jpg'),
( 'Class - 6th', 'Subjects - Science, Maths, English, Social Science', 2, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Easy', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/whmTQHB.jpg'),
( 'Class - 9th', 'Subjects - Science, Maths, English, Sanskrit', 5, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Intermediate', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/Eii0vu2.png'),
( 'JEE Batch', 'Subjects - Physics, Chemistry, Maths', 8, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Advance', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/Sot9Ipu.png'),
( 'Class - 7th', 'Subjects - Science, Maths, English, Social Science',3, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Easy', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/e6Npmfl.jpg'),
( 'Class - 10th', 'Subjects - Science, Maths, English, Sanskrit', 1, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Intermediate', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/sfVxuEk.png'),
( 'CET Batch', 'Subjects - Physics, Chemistry, Maths', 6, 'Our Classes are taught by master teachers with engaging concept visualizations, LIVE quizzes and leaderboards & Doubts solved LIVE by class teachers. We also offer test series which are created to deliver the best results. Get detailed reports, analysis and insights for best outcome.', 'Advance', 'https://www.youtube.com/live/oYinHSy6waI?feature=share', 'https://i.imgur.com/oF0DSFN.png');
-- INSERT TUITION
INSERT INTO tuition (user_id, course_id, date) VALUES (2, 6, '2023-02-16' ),
                                                        ( 2, 7, '2023-02-16');